
services:
  # ----------------------
  # PostgreSQL
  # ----------------------
  postgres:
    image: postgres:14
    profiles: ["node1"]
    container_name: snp-dwh-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ----------------------
  # Spark master
  # ----------------------
  spark-master:
    container_name: snp-dwh-spark-master
    profiles: ["node1"]
    build: ./spark
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark/spark_jobs:/opt/spark-apps
      - ./spark/spark_jobs/jars:/opt/spark-apps/jars

  # ----------------------
  # Spark worker
  # ----------------------
  spark-worker:
    container_name: snp-dwh-spark-worker
    profiles: ["node1"]
    build: ./spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2         
      - SPARK_WORKER_MEMORY=4G
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./spark/spark_jobs:/opt/spark-apps
      - ./spark/spark_jobs/jars:/opt/spark-apps/jars

  # ----------------------
  # Spark worker 2
  # ----------------------
  spark-worker-2:
    container_name: snp-dwh-spark-worker-2
    profiles: ["node1"]
    build: ./spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2         
      - SPARK_WORKER_MEMORY=4G       
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - spark-master
    ports:
      - "8083:8081"   # Cambia el puerto web UI para evitar conflicto
    volumes:
      - ./spark/spark_jobs:/opt/spark-apps
      - ./spark/spark_jobs/jars:/opt/spark-apps/jars
  # ----------------------
  # Airflow Init
  # ----------------------
  airflow-init:
    build: ./airflow
    profiles: ["node1"]
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=VmGZmplT2scTE2VQGpOb4qiGDA-37G1J9RldbdjOYSA=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_ENABLED=False
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - ./spark_jobs:/opt/airflow/spark_jobs
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -c "
        if airflow db check > /dev/null 2>&1; then
          echo 'La base de datos ya está inicializada, ejecutando upgrade...';
          airflow db upgrade;
        else
          echo 'Inicializando la base de datos...';
          airflow db init;
        fi
      "
    healthcheck:
      test: ["CMD-SHELL", "airflow db check || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ----------------------
  # Airflow Webserver
  # ----------------------
  airflow-webserver:
    container_name: snp-dwh-airflow-webserver
    profiles: ["node1"]
    build: ./airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=VmGZmplT2scTE2VQGpOb4qiGDA-37G1J9RldbdjOYSA=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_ENABLED=False
    depends_on:
      - airflow-init
    ports:
      - "8082:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - ./spark_jobs:/opt/airflow/spark_jobs
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -c "airflow webserver"

  # ----------------------
  # Airflow Scheduler
  # ----------------------
  airflow-scheduler:
    container_name: snp-dwh-airflow-scheduler
    profiles: ["node1"]
    build: ./airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=VmGZmplT2scTE2VQGpOb4qiGDA-37G1J9RldbdjOYSA=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_ENABLED=False
    depends_on:
      - airflow-init
      - airflow-webserver
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - ./spark_jobs:/opt/airflow/spark_jobs
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -c "airflow scheduler"

  # ----------------------
  # Hadoop Namenode
  # ----------------------
  snp-dwh-hadoop-namenode-1:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    profiles: ["node1"]
    ports:
      - "9870:9870"
      - "8020:8020"
    container_name: snp-dwh-hadoop-namenode-1
    environment:
      - CLUSTER_NAME=dev-hadoop
      - CORE_CONF_fs_defaultFS=hdfs://snp-dwh-hadoop-namenode-1:8020
      - CORE_CONF_hadoop_http_staticuser_user=root
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./sftp/sftp-data:/sftp-data

  # ----------------------
  # Hadoop Datanode
  # ----------------------
  snp-dwh-hadoop-datanode-1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    profiles: ["node1"]
    container_name: snp-dwh-hadoop-datanode-1
    depends_on:
      - snp-dwh-hadoop-namenode-1
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://snp-dwh-hadoop-namenode-1:8020
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_datanode_hostname=snp-dwh-hadoop-datanode-1
      - HDFS_CONF_dfs_datanode_use_datanode_hostname=false
      - HDFS_CONF_dfs_client_use_datanode_hostname=false
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - ./sftp/sftp-data:/sftp-data

  # ----------------------
  # SFTP
  # ----------------------
  sftp:
    image: atmoz/sftp
    profiles: ["node1"]
    container_name: sftp
    ports:
      - "2222:22"
    volumes:
      - ./sftp/sftp-data:/home/urbadigital/upload
    command: urbadigital:password:1001

volumes:
  postgres_data:
  hadoop_namenode:
  hadoop_datanode:
  airflow_logs:
