
services:
  postgres:
    profiles: ["node1"]
    build: ./postgres 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



  spark-master:
    build: ./spark
    profiles: ["node1"]
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=${SPARK_MASTER_PORT}
    ports:
      - "${SPARK_UI_PORT}:8080"
      - "${SPARK_MASTER_PORT}:7077"
    volumes:
      - ./spark/spark_jobs:/opt/spark-apps
      - ./spark/spark_jobs/jars:/opt/spark-apps/jars



  spark-worker:
    build: ./spark
    profiles: ["node1"]
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4g
      - SPARK_WORKER_CORES=4
    depends_on:
      - spark-master
    ports:
      - "${SPARK_WORKER_UI_PORT}:8081"
    volumes:
      - ./spark/spark_jobs:/opt/spark-apps
      - ./spark/spark_jobs/jars:/opt/spark-apps/jars



  airflow-webserver:
    build: ./airflow
    profiles: ["node1"]
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_ENABLED=False
    depends_on:
      - postgres
    ports:
      - "${AIRFLOW_WEB_PORT}:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - ./spark_jobs:/opt/airflow/spark_jobs
      - /var/run/docker.sock:/var/run/docker.sock

    command: webserver


  airflow-scheduler:
    build: ./airflow
    profiles: ["node1"]
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_ENABLED=False

    depends_on:
      - postgres
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - ./spark_jobs:/opt/airflow/spark_jobs
      - /var/run/docker.sock:/var/run/docker.sock

    command: scheduler


  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    profiles: ["node2"]
    environment:
      - CLUSTER_NAME=dev-hadoop
    ports:
      - "${HADOOP_NAMENODE_HTTP_PORT}:9870"
      - "${HADOOP_NAMENODE_RPC_PORT}:8020"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./sftp/sftp-data:/sftp-data



  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    profiles: ["node2"]
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:${HADOOP_NAMENODE_RPC_PORT}
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_replication=1
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./sftp/sftp-data:/sftp-data
    depends_on:
      - hadoop-namenode



  sftp:
    image: atmoz/sftp
    profiles: ["node2"]
    ports:
      - "${SFTP_PORT}:22"
    volumes:
      - /var/snp-dwh/sftp/sftp-data:/home/urbadigital/upload

    command: urbadigital:password:1001



volumes:
  postgres_data:
  hadoop_namenode:
  hadoop_datanode:
  airflow_logs:
